CELL_MAX_VALUE = 2**8
ARRAY_LENGTH = 30000

array = [0] * ARRAY_LENGTH
pointer = 0
output = []

array[pointer] = CELL_MAX_VALUE - 1 if array[pointer] == 0 else array[pointer] - 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1

while array[pointer] > 0:
    
    while array[pointer] > 0:
        pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
        pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        
        while array[pointer] > 0:
            pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
            
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        
        while array[pointer] > 0:
            pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
            
        pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
        array[pointer] = CELL_MAX_VALUE - 1 if array[pointer] == 0 else array[pointer] - 1
        
    pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    
    while array[pointer] > 0:
        pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
        
    pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    
    while array[pointer] > 0:
        pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
        
    pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1

while array[pointer] > 0:
    pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
    
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1

while array[pointer] > 0:
    
    while array[pointer] > 0:
        pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
        pointer = 0 if pointer == ARRAY_LENGTH - 1 else pointer + 1
        array[pointer] = CELL_MAX_VALUE - 1 if array[pointer] == 0 else array[pointer] - 1
        
    pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    array[pointer] = 0 if array[pointer] == CELL_MAX_VALUE - 1 else array[pointer] + 1
    output.append(chr(array[pointer]))
    pointer = ARRAY_LENGTH - 1 if pointer == 0 else pointer - 1
    

print(''.join(output))
